/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matematica;
import java.util.Scanner;

public class App {

    
    public String calculadora(int valor1, int valor2) {
      
        System.out.println("A soma dos valores é: " + (valor1 + valor2));
       
         System.out.println("A subtração dos valores é: " + (valor1 - valor2));
       
         System.out.println("A multiplicação dos valores é: " + (valor1 * valor2));
        
         System.out.println("A divisão dos valores é: " + (valor1/valor2));
         return "";
    };

    public static void main(String[] args) {
        int valor1;
        int valor2;
        Scanner leitor = new Scanner(System.in);
        
        System.out.print("Escreva o primeiro número: ");
        valor1 = leitor.nextInt();
        System.out.print("Escreva o segundo numero: ");
        valor2 = leitor.nextInt();
        
        new App().calculadora(valor1, valor2);
        
     };
}
